---
- hosts: all
  ignore_errors: true
  tasks:
    - name: hostname
      debug:
          var: ansible_hostname

    - name: fstab backup
      copy:
        src: /etc/fstab
        remote_src: true
        dest: /etc/fstab_bkp

    - name:  resolv.conf backup
      copy:
        src: /etc/resolv.conf
        remote_src: true
        dest: /etc/resolv.conf_bkp

    - name: Check uptime of remote server
      shell: uptime
      register: command_output

    - debug:
          var: command_output.stdout_lines

    - name: Check kernal version
      shell: uname -r
      register: command_output_before

    - debug:
          var: command_output_before.stdout_lines

    - name: Updating all packages
      yum:
        name: '*'
        state: latest

    - name: Rebooting host(s).
      shell: sleep 2 && /sbin/shutdown -r now "Reboot required for updated kernel." && sleep 2
      async: 20
      poll: 0
    - name: Waiting for host(s) to reboot
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: check kernal version
      shell: uname -r
      register: command_output_after

    - debug:
            var: command_output_after.stdout_lines
    - name: check uptime
      shell: uptime
      register: command_output
    - debug:
            var: command_output.stdout_lines
